site_name: Data Structures

theme:
  name: "material"
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.tabs
    - navigation.top
    - palette.toggle
    - navigation.footer
    - navigation.sidebar
    - navigation.expand

nav:
  - Home: index.md
  - Python:
    - Introduction: python/index.md
    - List: python/list.md
    - Tuple: python/tuple.md
    - Set: python/set.md
    - Dictionary: python/dictionary.md

  - C++:
    - Introduction: cpp/index.md
    - Array: cpp/array.md
markdown_extensions:
  - toc:
      permalink: True
  - codehilite


repo_url: https://github.com/SnakeByteDev/datastructures

extra:
  generator: false
